project:
  type: website
  output-dir: docs
  resources:
    - environmental_conditions.csv
    - closure_history.csv
    - data/images/**
    - data/json/**
    - data/resources/**

website:
  title: "TurtleWatch"
  navbar:
    right:
      - href: index.qmd
        text: " "
      - href: background.qmd
        text: Background
      - href: closure_rules.qmd
        text: Closure Rules
      - href: closure_status.qmd
        text: Conservation Area Status
      - href: data_dashboard.qmd
        text: Data Dashboard
      - href: data_dashboard2.qmd
        text: Data Dashboard2

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    include-after-body: footer.html



